PROGRAM TESTE_ARRAY
  INTEGER VETOR(5), I, MAIOR_VAL, BUSCAMAX
  
  PRINT *, 'INTRODUZA 5 NUMEROS INTEIROS:'
  
  DO 10 I = 1, 5
    READ *, VETOR(I)
10 CONTINUE

  MAIOR_VAL = BUSCAMAX(VETOR, 5)
  
  PRINT *, 'O MAIOR VALOR ENCONTRADO FOI: ', MAIOR_VAL
END

INTEGER FUNCTION BUSCAMAX(A(5), N)
  INTEGER A(5), N, J, ATUAL
  
  ATUAL = A(1)
  
  DO 20 J = 2, N
    IF (A(J) .GT. ATUAL) THEN
      ATUAL = A(J)
    ENDIF
20 CONTINUE

  BUSCAMAX = ATUAL
  RETURN
END