PROGRAM TEST_MATRIZ
  INTEGER M(3,3)
  INTEGER I, J, VAL
  
  PRINT *, 'PREENCHENDO MATRIZ 3X3:'
  
  DO 20 I = 1, 3
    DO 10 J = 1, 3
      M(I,J) = I * 10 + J
10  CONTINUE
20 CONTINUE

  PRINT *, 'CONTEUDO DA MATRIZ:'
  DO 40 I = 1, 3
    DO 30 J = 1, 3
      VAL = M(I,J)
      PRINT *, 'M(', I, ',', J, ') = ', VAL
30  CONTINUE
40 CONTINUE

END
